### ISSUE TITLE
(DigiDoc4j, JDigiDoc) Investigate JDD DDOC 1.0 validation issue in DD4j 1.0.4: 

### ISSUE THREAD

**Issue by priitr** [open-eid/SiVa#11]
org.bouncycastle.cert.ocsp.OCSPException: exception processing sig: java.lang.IllegalStateException: attempt to get non-octet aligned data from BIT STRING

Further details: 
https://www.pivotaltracker.com/story/show/125537231

**Comment by naare** [comment]
This issue is fixed with DD4J 3.0.0 integration to SiVa available on development branch.
