### ISSUE TITLE
(DigiDoc4j) Improve API to return validation parameters

### ISSUE THREAD

**Issue by priitr** [open-eid/SiVa#14]
Add new methods to dd4j API for accessing the following Signature information (currently this information is resolved as a workaround through underlying libraries):
• getSignatureLevel - should return the signature's legal qualification level, e.g. AdES, AdESqc, QES. Note that this value is not detected in case of JDigiDoc library and DDOC documents.
• getIndication - get the overall validation result (TOTAL-PASSED/TOTAL-FAILED/INDETERMINATE)
• getSubIndication - get the signature validation subindication. This is (probably) returned only in case of error (and warning) situations. Note that this value is not returned by JDigiDoc library and DDOC documents.

Feature request in Digidoc4j: https://www.pivotaltracker.com/story/show/123789261

**Comment by Madis26** [comment]
Now fixed. Signatures include signatureLevel, Indication and subIndication information.
Tested commit 9a2dd16637a48560f18768c54569150a30afd25f
Sample:
"signatures": [
                {
                    "id": "S0",
                    "signatureFormat": "XAdES_BASELINE_LT",
                    "signatureLevel": "INDETERMINATE_QESIG",
                    "signedBy": "ŽAIKOVSKI,IGOR,37101010021",
                    "indication": "INDETERMINATE",
                    "subIndication": "TRY_LATER",
                    "errors": [
                        {
                            "content": "No revocation data for the certificate"
                        }
                    ],
