### ISSUE TITLE
(DigiDoc4j) Digidoc4j does not allow detecting of INDETERMINATE signature status

### ISSUE THREAD

**Issue by priitr** [open-eid/SiVa#15]
Digidoc4j. It should be possible to return more specific signature status if the validation result is indeterminate. Currently only yes no valid is possible.

Feature request:
https://www.pivotaltracker.com/story/show/129437879

**Comment by Madis26** [comment]
Bdoc signatures indication can be INDETERMINATE now
Example: "signatures": [
                {
                    "id": "S0",
                    "signatureFormat": "XAdES_BASELINE_LT",
                    "signatureLevel": "INDETERMINATE_QESIG",
                    "signedBy": "MÄNNIK,MARI-LIIS,47101010033",
                    "indication": "INDETERMINATE",
                    "subIndication": "NO_POE",
