### ISSUE TITLE
(DigiDoc4j) Improve digidoc4j validation report

### ISSUE THREAD

**Issue by priitr** [open-eid/SiVa#16]
Digidoc4j validation report needs improvments.

Feature request:
https://www.pivotaltracker.com/story/show/118940113

Requested features:
1. The final validation result in Indication' field doesn't take into account possible manifest validation errors nor errors that may occur in AdditionalValidationResult errors.
2. Add BestSignatureTime to TM signature validation report

**Comment by Madis26** [comment]
2. BestSignatureTime added to validation detailed and simple report.
