### ISSUE TITLE
(DigiDoc4j, DSS) DSS doesn't properly validate manifest.xml

### ISSUE THREAD

**Issue by priitr** [open-eid/SiVa#18]
(DigiDoc4j, DSS) DSS doesn't properly validate manifest.xml, including not checking that data files in container would be listed in manifest.xml

Related issues:
https://esig-dss.atlassian.net/browse/DSS-842,
https://esig-dss.atlassian.net/browse/DSS-932

**Comment by Madis26** [comment]
Fixed in warning level.
Tested SiVa commit 9a2dd16637a48560f18768c54569150a30afd25f

"warnings": [
                        {
                            "content": "All files are not signed!"
                        }
