### ISSUE TITLE
(DigiDoc4j, DSS) OCSP revocation errors are not included in simple report

### ISSUE THREAD

**Issue by priitr** [open-eid/SiVa#19]
(DigiDoc4j, DSS) OCSP revocation errors are not included in simple report

https://esig-dss.atlassian.net/browse/DSS-922, https://www.pivotaltracker.com/n/projects/1110130/stories/129526189

**Comment by Madis26** [comment]
The simple report includes revocation error now.
"signatures": [
                {
                    "id": "S0",
                    "signatureFormat": "XAdES_BASELINE_LT",
                    "signatureLevel": "INDETERMINATE_QESIG",
                    "signedBy": "MÄNNIK,MARI-LIIS,47101010033",
                    "indication": "INDETERMINATE",
                    "subIndication": "NO_POE",
                    "errors": [
                        {
                            "content": "The past signature validation is not conclusive!"
                        }
                    ],
