### ISSUE TITLE
(DigiDoc4j) BDOC with time-stamp does not return proper warning when ocsp and timestamp difference exceeds 15m

### ISSUE THREAD

**Issue by priitr** [open-eid/SiVa#21]
(DigiDoc4j) In case of BDOC with time-stamp, the validation warning is not returned if time difference between time-stamp and OCSP issuance times exceeds 15 minutes: https://www.pivotaltracker.com/story/show/130098445

**Comment by Madis26** [comment]
An error is given now.

"errors": [
                        {
                            "content": "The revocation information is not considered as 'fresh'."
                        }
                    ],
                    "signatureScopes": [
                        {
                            "name": "0123456789~#%&()=`@{[]}'.txt",
                            "scope": "FullSignatureScope",
                            "content": "Full document"
                        }
                    ],
                    "claimedSigningTime": "2014-11-07T13:17:55Z",
                    "info": {
                        "bestSignatureTime": "2014-11-07T13:18:01Z"
                    }
                }
            ],
