### ISSUE TITLE
(X-Road Asicverifier) Values of some validation report fields are not accessible via the X-Road library's API

### ISSUE THREAD

**Issue by priitr** [open-eid/SiVa#25]
(X-Road Asicverifier) Values of some validation report fields are not accessible via the X-Road library's API:
1. SignatureFormat – Format and profile (according to Baseline Profile) of the signature. Currently, hard coded values are used in the report.
2. SignatureLevel – Indication whether the signature is Advanced electronic Signature (AdES), AdES supported by a Qualified Certificate (AdES/QC) or a Qualified electronic Signature (QES). Currently, the value is left empty, as the library doesn't enable determining legal level of the signature then POLv2 validation policy (only QES level signatures are accepted) is not supported for X-Road signatures.
3. Indication, Errors and Warnings - in error situations, the verification process results in a CodedException extends RuntimeException. This Exception always contains a fault code String but it’s how should we determine if we should result in INDETERMINATE or TOTAL-FAILED result? Also since the rest of the verification process is not completed after the exception we only ever know the single error that was reached first. Also we can’t get warnings as we do in DSS.
4. SubIndication – Additional subindication in case of failed or indeterminate validation result, according to EN 319 102-1 "Table 6: Validation Report Structure and Semantics".
5. SignatureScope - Contains information of the original data that is covered by the signature. Currently, a hard-coded value is used.
6. ClaimedSigningTime - Claimed signing time, i.e. user’s computer time during signature creation.

**Comment by naare** [comment]
In SIVA 3.2.0 these fields are removed from validation report.

**Comment by naare** [comment]
In SIVA 3.6.0 x-road container validation is removed.
