### ISSUE TITLE
(X-Road Asicverifier) Qualified electronic signature validation process - the Asicverifier library doesn't check if the issuer's certificate was issued by a qualified trust service provider

### ISSUE THREAD

**Issue by priitr** [open-eid/SiVa#26]
(X-Road Asicverifier) Qualified electronic signature validation process - the Asicverifier library doesn't check if the issuer's certificate was issued by a qualified trust service provider (i.e. based on the data in TL trust list).

**Comment by naare** [comment]
In SIVA 3.6.0 x-road container validation is removed.
