### ISSUE TITLE
(DSS) Add validated certificate chain to DSS validation report

### ISSUE THREAD

**Issue by kristiu** [open-eid/SiVa#28]
According to EN 319 102 Part 1, the SVA should return the validated certificate chain to the DA in case of TOTAL-PASSED indication, see also table 5 on page 31:
"The validation process shall output the validated certificate chain, including the signing certificate, used in the validation process. In addition, the validation process may provide the result of the validation for each of the validation constraints. The validation process should provide the DA access to the signed attributes present in the signature, the identity of the signer and the signing certificate chain."

The DSS Diagnostic Data Report does indeed contain Id values of the validated certificates (including the Id of the signer’s certificate) but the certificates themselves are not included. 
Please add the validated certificate chain to the report.

External DSS ticket: https://esig-dss.atlassian.net/browse/DSS-878
External DigiDoc4j ticket: https://www.pivotaltracker.com/story/show/137779705

**Comment by naare** [comment]
SIVA 3.2.0 returns the used trust chain info in Diagnostic report. However, it does not include the certificates themselves.

**Comment by naare** [comment]
SIVA 3.3.0 returns used certificates in Simple report ValidationConclusion.
