### ISSUE TITLE
(DSS) expired certificate masks QC/SSCD constraint failure

### ISSUE THREAD

**Issue by allanjuhanson** [open-eid/SiVa#29]
QC/SSCD constraint validation is not performed when the signing certificate is expired. This causes non QC/SSCD compliant signatures to pass validation when the signing certificate is expired.

external DSS ticket: https://ec.europa.eu/cefdigital/tracker/browse/DSS-1134

**Comment by naare** [comment]
Tested okay with DSS 5.0 which is included as 5.0.d4j.1
