### ISSUE TITLE
The certificate path is not trusted!

### ISSUE THREAD

**Issue by rafael747** [open-eid/SiVa#40]
I changed the "siva-keystore.jks" with another one, with the required ca's to validate a document.
I also set the same password as the old one.

But I am still getting the message: "The certificate path is not trusted!"

certificateChain: (of the document)
"0C32A4BA94B9EA5FB681DD3A55E6CCB103AA7F8BEF5CC8E9780A2ACDE587CB1B"
"56305ECE76E0A9E123542F1ABA11829FC75359D9368FAD24653DAE30B52F72ED"
"FB47D92A9909FD4FA9BEC02737543E1F3514CED747407A8D9CFA397B0915067C"

```
openssl x509 -noout -fingerprint -sha256 -inform pem -in AC_Soluti.crt          
SHA256 Fingerprint=56:30:5E:CE:76:E0:A9:E1:23:54:2F:1A:BA:11:82:9F:C7:53:59:D9:36:8F:AD:24:65:3D:AE:30:B5:2F:72:ED

openssl x509 -noout -fingerprint -sha256 -inform pem -in AC_Soluti_Multipla_v1.crt 
SHA256 Fingerprint=0C:32:A4:BA:94:B9:EA:5F:B6:81:DD:3A:55:E6:CC:B1:03:AA:7F:8B:EF:5C:C8:E9:78:0A:2A:CD:E5:87:CB:1B

openssl x509 -noout -fingerprint -sha256 -inform pem -in ICP-Brasilv2.crt 
SHA256 Fingerprint=FB:47:D9:2A:99:09:FD:4F:A9:BE:C0:27:37:54:3E:1F:35:14:CE:D7:47:40:7A:8D:9C:FA:39:7B:09:15:06:7C
```

```
keytool -import -file ICP-Brasilv2.crt -keystore nova.jks -storepass "siva-keystore-password" -alias icpv2
keytool -import -file AC_Soluti.crt -keystore nova.jks -storepass "siva-keystore-password" -alias acsoluti
keytool -import -file AC_Soluti_Multipla_v1.crt -keystore nova.jks -storepass "siva-keystore-password" -alias acsoluti_m
```

```

keytool -list -keystore nova.jks 
Enter keystore password:  
Keystore type: jks
Keystore provider: SUN

Your keystore contains 3 entries

acsoluti_m, Jul 29, 2019, trustedCertEntry, 
Certificate fingerprint (SHA1): AF:9C:7E:13:EE:62:CD:E7:6B:25:AB:34:B6:31:41:B0:0A:F6:DE:1B
icpv2, Jul 29, 2019, trustedCertEntry, 
Certificate fingerprint (SHA1): A9:82:2E:6C:69:33:C6:3C:14:8C:2D:CA:A4:4A:5C:F1:AA:D2:C4:2E
acsoluti, Jul 29, 2019, trustedCertEntry, 
Certificate fingerprint (SHA1): 39:F4:0F:D3:13:2B:CF:73:67:2E:04:ED:4C:97:7F:CC:A1:78:C2:45

```

`cp nova.jks siva-keystore.jks`

What am I missing?

**Comment by naare** [comment]
You can not add trusted certificates to SIVA through the keystores. SIVA uses European list of the list (LOTL) for retrieving trusted certificates. siva-keystore.jks is used to store trusted LOTL signer certificates.

**Comment by rafael747** [comment]
So, there is no way to include a root certificate of another non European country?

**Comment by naare** [comment]
There are two options:
1) Create your own LOTL and custom trust list and configure SIVA to use that as a trust source. This is rather complicated as the lotl and trust list must be with correct structure and signatures.
2) Add certificates through the CustomCertificatesLoader class (hardcoded trust) and start the  SIVA in TEST mode.

Sadly there is no good and easy way to trust certificates outside of EU LOTL system.
